name: Trigger Jenkins Job

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Jenkins job name'
        required: true
        default: 'default-job-name'

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: ${{ github.event.inputs.job_name }}
          method: 'POST'
