name: Trigger Jenkins Job

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Jenkins job name'
        required: true
        default: 'default-job-name'

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Jenkins Crumb
        id: fetch-crumb
        run: |
          CRUMB=$(curl -s -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" "${{ secrets.JENKINS_URL }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
          echo "CRUMB=$CRUMB"
          echo "::set-output name=crumb::$CRUMB"

      - name: Trigger Jenkins Job via Curl
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ github.event.inputs.job_name }}/build" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          -H "${{ steps.fetch-crumb.outputs.crumb }}" \
          --data-urlencode "token=${{ secrets.JENKINS_TOKEN }}"
