name: Trigger Jenkins Job

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Jenkins job name'
        required: true
        default: 'default-job-name'

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job via Curl
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ github.event.inputs.job_name }}/buildWithParameters" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          --data-urlencode "token=${{ secrets.JENKINS_TOKEN }}"
